---
# Create DNS challenges for DNS provider Amazon Route53
- name: Creating challenge DNS entries for domains {{ ', '.join(domains) }} via DNSMadeEasy
  connection: local
  dnsmadeeasy:
    account_key: "{{ dme_account_key }}"
    account_secret: "{{ dme_account_secret }}"
    # This is fragile, and will only work for 2-level domain (eg: corp.com, NOT corp.co.uk )
    domain: "{{ item.value['dns-01']['record'] |regex_replace('^(?:.*\\.|)([^.]+\\.[^.]+)$', '\\1') }}"
    record_ttl: 60
    record_type: TXT
    record_name: "{{ item.value['dns-01']['record'] |regex_replace('^(.*)(\\.[^.]+\\.[^.]+)$', '\\1') }}" 
    record_value: "{{ item.value['dns-01']['resource_value'] }}"
    state: present
  # Need dnsmadeeasy module fixed (https://github.com/ansible/ansible/issues/58305)
  run_once: True
  with_dict: "{{ lets_encrypt_challenge.challenge_data }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs

- name: Wait for DNS entries to become available
  shell: "dig txt {{ item.value['dns-01']['record'] }} +short @8.8.8.8"
  register: dig_result
  until: "item.value['dns-01']['resource_value'] in dig_result.stdout"
  retries: 60
  delay: 5
  with_dict: "{{ lets_encrypt_challenge.challenge_data }}"
